export const currencies = {
	MYR: { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM', decimals: 2 },
	USD: { code: 'USD', name: 'US Dollar', symbol: '$', decimals: 2 },
	SGD: { code: 'SGD', name: 'Singapore Dollar', symbol: 'S$', decimals: 2 },
	EUR: { code: 'EUR', name: 'Euro', symbol: '€', decimals: 2 },
	GBP: { code: 'GBP', name: 'British Pound', symbol: '£', decimals: 2 },
	AUD: { code: 'AUD', name: 'Australian Dollar', symbol: 'A$', decimals: 2 },
	JPY: { code: 'JPY', name: 'Japanese Yen', symbol: '¥', decimals: 0 },
	CNY: { code: 'CNY', name: 'Chinese Yuan', symbol: '¥', decimals: 2 },
	HKD: { code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK$', decimals: 2 },
	TWD: { code: 'TWD', name: 'New Taiwan Dollar', symbol: 'NT$', decimals: 2 },
	KRW: { code: 'KRW', name: 'South Korean Won', symbol: '₩', decimals: 0 },
	INR: { code: 'INR', name: 'Indian Rupee', symbol: '₹', decimals: 2 },
	THB: { code: 'THB', name: 'Thai Baht', symbol: '฿', decimals: 2 },
	IDR: { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp', decimals: 0 },
	PHP: { code: 'PHP', name: 'Philippine Peso', symbol: '₱', decimals: 2 },
	VND: { code: 'VND', name: 'Vietnamese Dong', symbol: '₫', decimals: 0 },
	BND: { code: 'BND', name: 'Brunei Dollar', symbol: 'B$', decimals: 2 },
	SAR: { code: 'SAR', name: 'Saudi Riyal', symbol: 'SAR', decimals: 2 },
	AED: { code: 'AED', name: 'UAE Dirham', symbol: 'AED', decimals: 2 },
	NZD: { code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ$', decimals: 2 },
	CAD: { code: 'CAD', name: 'Canadian Dollar', symbol: 'CA$', decimals: 2 },
	CHF: { code: 'CHF', name: 'Swiss Franc', symbol: 'CHF', decimals: 2 },
	SEK: { code: 'SEK', name: 'Swedish Krona', symbol: 'kr', decimals: 2 },
	NOK: { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr', decimals: 2 },
	DKK: { code: 'DKK', name: 'Danish Krone', symbol: 'kr', decimals: 2 },
	BRL: { code: 'BRL', name: 'Brazilian Real', symbol: 'R$', decimals: 2 },
	ZAR: { code: 'ZAR', name: 'South African Rand', symbol: 'R', decimals: 2 },
	TRY: { code: 'TRY', name: 'Turkish Lira', symbol: '₺', decimals: 2 },
	RUB: { code: 'RUB', name: 'Russian Ruble', symbol: '₽', decimals: 2 },
	PKR: { code: 'PKR', name: 'Pakistani Rupee', symbol: 'Rs', decimals: 2 },
	BDT: { code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳', decimals: 2 },
	NGN: { code: 'NGN', name: 'Nigerian Naira', symbol: '₦', decimals: 2 },
	EGP: { code: 'EGP', name: 'Egyptian Pound', symbol: 'E£', decimals: 2 },
	KES: { code: 'KES', name: 'Kenyan Shilling', symbol: 'KSh', decimals: 2 },
	GHS: { code: 'GHS', name: 'Ghanaian Cedi', symbol: 'GH₵', decimals: 2 },
} as const;

export type CurrencyCode = keyof typeof currencies;

export const currencyList = Object.values(currencies);
